spring.application.name=jdbc1
jdbc.url=jdbc:postgresql://localhost:54317/jdbc
jdbc.driverClassName=org.postgresql.Driver
jdbc.initialSize=5
jdbc.username=postgres
jdbc.password=1

# Liquibase
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml