## My current database configuration is:
# db.name=jdbc
# db.port=54317
# db.user=postgres
# db.password=1

## You should actualize and configure your database here:
spring.application.name=jdbc1
jdbc.url=jdbc:postgresql://localhost:54317/jdbc
jdbc.driverClassName=org.postgresql.Driver
jdbc.initialSize=5
jdbc.username=postgres
jdbc.password=1

# Liquibase for db migration:
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml